openapi: 3.0.3

info:
  title: Vaping Stamps API [Test only]
  version: "1.0"
  description: |
    # Overview
    The Vaping Duty Stamps - Approval Status Check API enables authorised stamp suppliers to verify whether a purchasing operator is currently approved to purchase vaping duty stamps.
    
    This API supports the verification of a purchasing operator’s approval status before an authorised stamp supplier issues the vaping duty stamps.

    This API exposes a single endpoint that allows the appointed stamp supplier
    to perform an approval status check against HMRC systems.

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox

tags:
  - name: Approval status verification
    description: |
      The Vaping Duty Stamps - Approval Status Check API provides a single endpoint that supports a daily approval status check against the relevant HMRC approval systems, to make sure that stamps are purchased by only operators with a valid approval status.
      
      Until this API is available in the production environment, the endpoint will be identified with the label **[Test only]**. This indicates that the endpoint is available purely for Test purposes only, and can not be used for live operational purposes.

paths:
  /misc/vaping/stamps/status:
    post:
      summary: Check purchasing operator approval status - [Test only]
      description: |
        This verifies if a purchasing operator is currently authorised to purchase vaping duty stamps.

        **Example request**

        `POST https://test-api.service.hmrc.gov.uk/misc/vaping/stamps/status`
        
        ### Test data
        This service can simulate various scenarios by supplying a **stampsReferenceNumber** in the request body of the service.
        
        *XI* can replace *GB*
        *C* can be replaced by other individual letters detailed in the schemas
        
        The table below gives example values for **stampsReferenceNumber** and a description of the scenario.
  
        | stampsReferenceNumber value      | Description of scenario                                                                                                                 |
        |----------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------|
        | GBVC0000200DS                    | Simulate the test environment to return a successful response with the approvalStatus attribute set to APPROVED.                        |
        | GBVC0000266DS                    | Simulate the test environment to return a successful response with the approvalStatus attribute set to NOT_APPROVED.                    |
        | GBVC0000422DS                    | Simulate a business error response in the test environment for scenarios where the requested **stampsReferenceNumber** cannot be found. |
        | GBVC1000422DS                    | Simulate a business error response in the test environment for scenarios where the requested vdsEmail cannot be found.                  |
        | GBVC2000422DS                    | Simulate a business error response in the test environment for scenarios where the same stampsReferenceNumber is called multiple times. |
        | GBVC0000500DS                    | Simulate a server error response in the test environment for scenarios where an Internal Server Error occurs from the API.              |
        | GBVC0000503DS                    | Simulate a downstream error response in the test environment for scenarios where an error from the downstream services occurs.          |
        
        The 'GBVC' prefix can end with different letters that refer to Entities that have requested the service. The below table display the mapping between these letters and entities.
        
        | Prefix         | Entity                  |
        |----------------|-------------------------|
        | GBVC           | Customs Warehouse       |
        | GBVE           | Excise Warehouse        |
        | GBVF           | Freeport                |
        | GBVM           | Manufacturer            |
        | GBVR           | UK rep                  |
        | XIV[C,E,F,M,R] | Northern Ireland entity |
        
        **NOTE**: 400 error scenarios can be simulated by sending requests containing missing or invalid HTTP headers and request field values.The response schema must be submitted as JSON and contain the following details.

      operationId: retrieveApprovalStatus

      security:
        - applicationRestricted: [ ]

      parameters:
        - $ref: "#/components/parameters/acceptHeader"
        - $ref: "#/components/parameters/authorizationHeader"
        - $ref: "#/components/parameters/contentType"

      requestBody:
        required: true
        description: |
          Vaping approval request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VDSDetails"
            example:
              {
                "vdsEmail": "test@test.com",
                "stampsReferenceNumber": "GBVC0000001DS"
              }

      responses:
        "200":
          description: Operator record found.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ApprovedOperatorResponse"
                  - $ref: "#/components/schemas/NotApprovedOperatorResponse"
              examples:
                  Approved:
                    value:
                      {
                        approvalStatus: "APPROVED",
                        businessName: "Example Trading Ltd",
                        addressLine1: "Address Line 1",
                        addressLine2: "Address Line 2",
                        addressLine3: "Address Line 3",
                        addressLine4: "Address Line 4",
                        addressLine5: "Address Line 5",
                        postCode: "SW1A 1AA",
                        contactName: "Jane Smith",
                        telephoneNumber: "+44 20 7946 0123",
                        stampsThreshold: 500000
                      }
                  NotApproved:
                    value:
                      {
                        approvalStatus: "NOT_APPROVED"
                      }


        "400":
          description: Client error — the request is malformed or fails validation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400ErrorResponse"
              example:
                {
                  "code": "BAD_REQUEST",
                  "message": "Request sent is invalid",
                  "errors": [ "001", "002", "003" ]
                }

        "401":
          description: Client error — authentication credentials are missing or invalid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                {
                  "code": "UNAUTHORISED",
                  "message": "Authentication credentials are missing or invalid."
                }

        "403":
          description: Client error — the client is authenticated but not authorised to perform this action.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              example:
                {
                  "code": "FORBIDDEN",
                  "message": "You are not authorised to access this resource."
                }

        "404":
          description: Not Found error - Requested endpoint does not exist in service.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundErrorResponse"
              example:
                {
                  "code": "MATCHING_RESOURCE_NOT_FOUND",
                  "message": "A resource with the name in the request can not be found in the API"
                }

        "415":
          description: Request error — Invalid Content-Type provided.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/415ErrorResponse"
              example:
                {
                  "statusCode": 415,
                  "message": "Expecting text/json or application/json body"
                }

        "422":
          description: Business error — no approval record exists with the combination of values provided.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/422ErrorResponse"
              example:
                {
                  "code": "UNPROCESSABLE_ENTITY",
                  "message": "The request has returned a business logic error.",
                  "errors": [ "001", "002", "003" ]
                }

        "500":
          description: Server error — an unexpected internal error occurred while processing the request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500ErrorResponse"
              example:
                {
                  "code": "INTERNAL_SERVER_ERROR",
                  "message": "<error message based on failure>"
                }

        "503":
          description: Downstream error — an error has occurred downstream from the API
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/503ErrorResponse"
              example:
                {
                  "code": "SERVER_ERROR",
                  "message": "Service unavailable"
                }

components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests
        using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.

        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints
        for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }

  parameters:
    acceptHeader:
      name: Accept
      in: header
      required: true
      description: "Specifies the API [version](/api-documentation/docs/reference-guide#versioning) and response format."
      schema:
        type: string
        enum:
          - application/vnd.hmrc.1.0+json
    authorizationHeader:
      name: Authorization
      in: header
      required: true
      description: "OAuth 2.0 Bearer token used to authorize access to the API."
      schema:
        type: string
        example: "Bearer f44d58e9f36c1b5c9b18a0400f43efdd"
    contentType:
      name: Content-Type
      in: header
      required: true
      description: "Specifies the response body format."
      schema:
        type: string
        enum:
          - application/json

  schemas:
    VDSDetails:
      type: object
      required:
        - vdsEmail
        - stampsReferenceNumber
      properties:
        vdsEmail:
          type: string
          pattern: "^[a-zA-Z0-9_.+-]{1,64}+@[a-zA-Z0-9-]{1,64}+\\.[a-zA-Z0-9-.]{1,64}+$"
          description: Contact email address of the purchasing operator.
        stampsReferenceNumber:
          type: string
          pattern: "^(GB|XI)V[CEFMR][0-9]{7}DS$"
          description: Unique vaping duty stamps approval identifier issued by HMRC.

    ApprovedOperatorResponse:
      type: object
      required:
        - approvalStatus
        - businessName
        - addressLine1
        - postCode
        - stampsThreshold
      
      example:
        {
          approvalStatus: "APPROVED",
          businessName: "Example Trading Ltd",
          addressLine1: "Address Line 1",
          addressLine2: "Address Line 2",
          addressLine3: "Address Line 3",
          addressLine4: "Address Line 4",
          addressLine5: "Address Line 5",
          postCode: "SW1A 1AA",
          contactName: "Jane Smith",
          telephoneNumber: "+44 20 7946 0123",
          stampsThreshold: 500000
        }

      properties:
        approvalStatus:
          type: string
          description: The current approval status of the purchasing operator.
          enum:
            - APPROVED
        
        businessName:
          type: string
          description: Registered name of the business associated with the purchasing operator.
        
        addressLine1:
          type: string
          description: First line of the business' address
        
        addressLine2:
          type: string
          description: Second line of the business' address
        
        addressLine3:
          type: string
          description: Third line of the business' address
        
        addressLine4:
          type: string
          description: Fourth line of the business' address
        
        addressLine5:
          type: string
          description: Fifth line of the business' address
        
        postCode:
          type: string
          description: Postal Code for the business' address
        
        contactName:
          type: string
          description: Primary contact name for the purchasing operator.
        
        contactTelephone:
          type: string
          description: Contact telephone number for the purchasing operator.
        
        stampsThreshold:
          type: number
          description: Approved purchase threshold for the maximum number of vaping duty stamps that the operator can purchase.

    NotApprovedOperatorResponse:
      type: object
      required:
        - approvalStatus

      example:
        {
          approvalStatus: "NOT_APPROVED"
        }
      properties:
        approvalStatus:
          type: string
          description: The current approval status of the purchasing operator.
          enum:
            - NOT_APPROVED

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string

    NotFoundErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string

    400ErrorResponse:
      type: object
      required:
        - code
        - message
        - errors
      properties:
        code:
          type: string
        message:
          type: string
        errors:
          type: array
          items:
            type: string
            enum: [ "001", "002", "003", "004", "005", "006", "007", "008", "009"]
          description: |
            * "001" - Missing Accept Header
            * "002" - Incorrect Accept Header
            * "003" - Missing Content-Type Header
            * "004" - Incorrect Content-Type Header
            * "005" - Missing stampsReferenceNumber
            * "006" - Incorrect stampsReferenceNumber
            * "007" - Missing vdsEmail
            * "008" - Incorrect vdsEmail
            * "009" - The vdsEmail is too long

    415ErrorResponse:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: number
        message:
          type: string


    422ErrorResponse:
      type: object
      required:
        - code
        - message
        - errors
      properties:
        code:
          type: array
          items:
            type: string
        message:
          type: string
        errors:
          type: array
          items:
            type: string
            enum: [ "001", "002", "003" ]
          description: |
            * "001" - **stampsReferenceNumber** not found in ETDS
            * "002" - vdsEmail not found in ETDS
            * "003" - Details for this stampsReferenceNumber have already been requested by the authorised stamp supplier

    500ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string

    503ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string

